CREATE TABLE likes(
    lid INT AUTO_INCREMENT PRIMARY KEY,
    pid INT,
    uid INT
);

ALTER TABLE likes ADD CONSTRAINT FOREIGN KEY (pid) REFERENCES posts(pid) ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE likes ADD CONSTRAINT FOREIGN KEY (uid) REFERENCES user_details(id) ON DELETE CASCADE
ON UPDATE CASCADE;